#!/usr/bin/env node
// Rebuild current media from public evidence + committed original audio.
// Optional build dependencies: Playwright Chromium and ffmpeg.
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto');
const {execFileSync}=require('node:child_process');const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),out=path.join(root,'docs/media'),source=path.join(out,'source');
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'fantasy-benefits-'));
const read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const benchmark=read('examples/v3-benchmark/results-800.json');const turns=read('examples/v3-benchmark/next-turn-800.json');const demo=read('docs/site/v3-demo.json');
const rows=benchmark.summary;const points=p=>Math.round(rows[p].starter_points.mean);const gain=p=>Math.round(rows.v3_live.starter_points.mean-rows[p].starter_points.mean);
const walker=Object.values(turns).find(p=>p.name==='Kenneth Walker III'),rice=Object.values(turns).find(p=>p.name==='Rashee Rice');
const wid=Object.keys(turns).find(k=>turns[k]===walker),rid=Object.keys(turns).find(k=>turns[k]===rice);
const wp=(100*rice.other_candidates_surviving_trials[wid]/rice.trials).toFixed(1),rp=(100*walker.other_candidates_surviving_trials[rid]/walker.trials).toFixed(1);
const ahead=benchmark.rows.filter(r=>r.policies.v3_live.starter_points>r.policies.disciplined_adp.starter_points).length;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const beats=read('docs/media/source/storyboard.json');
const players=demo.after.candidates.map((p,i)=>`<div class="player ${i?'':'first'}"><div><small>${i?'ALTERNATIVE':'RECOMMENDED PICK'} · ${esc(p.pos)}</small><h3>${esc(p.name)}</h3></div><b>${p.projection.toFixed(0)}<small>projected pts</small></b></div>`).join('');
const frames=[
 ['FREE & OPEN SOURCE','Your next pick<br>shapes your<br><em>whole team.</em>',`<div class="box"><p>Targets. Backups.<br>A plan for your league.</p></div>`,'Fantasy Draft Analyst · V3'],
 ['YOUR DRAFT DECISIONS ADD UP',`<span class="huge">+${gain('disciplined_adp')}</span><span class="subhead">projected starting-lineup points</span>`,`<div class="box comparison"><div><span>Disciplined ADP</span><b>${points('disciplined_adp').toLocaleString()}</b></div><div class="highlight"><span>Fantasy Draft Analyst</span><b>${points('v3_live').toLocaleString()}</b></div></div>`,'800 simulated drafts · 12-team half-PPR · All 12 draft positions'],
 ['PICKENS TAKEN AT 19','Your target’s gone.<br><em>Your backup’s ready.</em>',players,'Saved example · Pick 20 · Your roster: Jonathan Taylor'],
 ['MAKE YOUR NEXT TWO PICKS WORK TOGETHER','Take Walker now.',`<div class="box odds"><div><strong>${wp}%</strong><p>Walker reaches pick 29<br>if you take Rice now.</p></div><div><strong>${rp}%</strong><p>Rice reaches pick 29<br>if you take Walker now.</p></div></div><p class="gain"><b>+${walker.paired_utility_difference.toFixed(1)} projected points</b><br>with the Walker-first path, across two picks.</p>`,'Simulated chances · 800 simulations per path'],
 ['CONSISTENT ACROSS THE DRAFT ROOM',`<span class="huge">${ahead}<span class="outof"> / 800</span></span><span class="subhead">stronger projected lineups</span>`,`<div class="box"><p>V3 finished ahead of disciplined ADP drafting in ${ahead} of ${benchmark.rooms} simulated drafts.</p></div>`,'Internal simulation · Positive average gain at all 12 draft positions'],
 ['YOUR LEAGUE. YOUR ROSTER. YOUR NEXT PICK.','Get the<br><em>free skill.</em>',`<div class="box"><h3>Prepare your draft plan</h3><p>Use an assistant with code execution.</p><h3>Update advice as you draft</h3><p>Run live mode with local Python.</p></div><p class="url">nicodeguyo.github.io/<br>fantasy-draft-analyst</p>`,'Free & open source · Choose your setup on the website']
];
const css=`*{box-sizing:border-box}body{margin:0;background:#0b1b33;color:#f7fafc;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;padding:65px;width:1080px;height:1350px;overflow:hidden}header{color:#8edb4b;font-size:23px;font-weight:800;letter-spacing:.06em;margin-bottom:48px}h1{font-family:Impact,'Arial Narrow',sans-serif;font-size:106px;font-weight:400;line-height:1.03;margin:0 0 44px}em{font-style:normal;color:#8edb4b}.huge{font-size:235px;display:block;letter-spacing:-.03em;color:#8edb4b}.subhead{display:block;font-family:inherit;font-size:66px;line-height:1.08;margin-top:18px}.outof{font-size:92px;color:#c7d4e3}.box{background:#142d47;border:1px solid #496078;border-radius:12px;padding:32px;margin:25px 0}.box p{font-size:39px;line-height:1.4;margin:10px 0}.box h3{font-size:37px;margin:8px 0}.box h3:not(:first-child){margin-top:28px}.comparison>div{display:flex;justify-content:space-between;gap:12px;padding:25px 0;border-bottom:1px solid #496078;align-items:center;font-size:30px}.comparison b{font-size:57px}.highlight{color:#8edb4b}.player{display:flex;justify-content:space-between;align-items:center;padding:26px 30px;background:#142d47;border:1px solid #496078;border-radius:9px;margin:18px 0;gap:15px}.player.first{border-left:8px solid #8edb4b}.player h3{font-size:43px;margin:8px 0}.player small{font-size:19px;color:#c7d4e3;display:block}.player b{font-size:58px;text-align:right}.player b small{font-size:17px;font-weight:500}.odds>div{display:flex;align-items:center;gap:30px;border-bottom:1px solid #496078;padding:22px 0}.odds strong{font-size:92px;color:#8edb4b;min-width:300px}.odds p{font-size:31px}.gain{font-size:35px;line-height:1.45}.gain b{color:#8edb4b;font-size:47px}.url{font-size:32px;line-height:1.3;color:#8edb4b}footer{position:absolute;left:65px;right:65px;bottom:110px;color:#c7d4e3;font-size:21px;line-height:1.4}.caption{position:absolute;bottom:26px;left:40px;right:40px;padding:18px 22px;border-radius:8px;background:#213c57;color:white;font-size:25px;line-height:1.25;font-weight:650}`;
(async()=>{const browser=await chromium.launch({headless:true});try{const page=await browser.newPage({viewport:{width:1080,height:1350}});
 for(let i=0;i<frames.length;i++){const [label,title,body,foot]=frames[i];await page.setContent(`<html><head><meta charset="utf-8"><style>${css}</style></head><body><header>${label}</header><main><h1>${title}</h1>${body}</main><footer>${foot} · September 7, 2026 projections</footer><div class="caption">${esc(beats[i].caption)}</div></body></html>`);
 const bottom=await page.locator('main').evaluate(e=>e.getBoundingClientRect().bottom);if(bottom>1170)throw Error(`Frame ${i} overflows: ${bottom}`);
 await page.screenshot({path:path.join(temp,`frame-${i}.png`)});if(i===1)await page.screenshot({path:path.join(out,'v3-video-poster.png')});if(i===2)await page.screenshot({path:path.join(out,'v3-decision.png')});}
 await page.setViewportSize({width:1280,height:640});await page.setContent(`<html><head><style>${css}body{width:1280px;height:640px;padding:45px 60px}header{font-size:22px;margin-bottom:15px}h1{font-size:170px;color:#8edb4b;margin:0}.socialsub{font-size:42px;margin:0;max-width:650px;line-height:1.15}.socialside{position:absolute;left:790px;right:60px;top:185px;font-size:27px;line-height:1.5;border-top:3px solid #8edb4b;padding-top:20px}footer{bottom:30px;font-size:18px}</style></head><body><header>FANTASY DRAFT ANALYST · FREE & OPEN SOURCE</header><h1>+${gain('disciplined_adp')}</h1><p class="socialsub">projected starting-lineup points<br>versus disciplined ADP drafting.</p><div class="socialside">Your next pick shapes<br>your whole team.<br><b>${ahead} / 800</b> stronger<br>projected lineups.</div><footer>Internal simulation · 800 drafts · 12-team half-PPR · All 12 draft positions · September 7 projections</footer></body></html>`);await page.screenshot({path:path.join(out,'social-preview-v3.png')});
 }finally{await browser.close()}
 const ff=args=>execFileSync('ffmpeg',['-v','error','-y',...args],{stdio:'pipe'});
 const visual=path.join(temp,'visual.mp4');ff(['-framerate','1','-i',path.join(temp,'frame-%d.png'),'-vf',"zoompan=z='1+0.012*mod(on,150)/149':d=150:s=1080x1350:fps=25",'-t','36','-c:v','libx264','-preset','fast','-crf','19','-pix_fmt','yuv420p',visual]);
 const music=path.join(temp,'music.wav');ff(['-stream_loop','-1','-i',path.join(source,'upbeat-original.flac'),'-t','36','-af','afade=t=in:d=0.5,afade=t=out:st=34:d=2,volume=0.22',music]);
 const mix=path.join(temp,'mix.wav');ff(['-i',path.join(source,'michael-narration.flac'),'-i',music,'-filter_complex','[0:a][1:a]amix=inputs=2:duration=first:normalize=0,loudnorm=I=-16:TP=-1.5:LRA=7[a]','-map','[a]',mix]);
 for(const [audio,name] of [[mix,'v3-walkthrough.mp4'],[music,'v3-walkthrough-music-only.mp4']])ff(['-i',visual,'-i',audio,'-map','0:v:0','-map','1:a:0','-c:v','copy','-c:a','aac','-b:a','192k','-t','36','-movflags','+faststart',path.join(out,name)]);
 ff(['-framerate','2/5','-i',path.join(temp,'frame-%d.png'),'-vf','scale=480:-1:flags=lanczos,split[a][b];[a]palettegen=stats_mode=diff[p];[b][p]paletteuse=dither=bayer','-loop','0',path.join(out,'v3-tour.gif')]);
 const time=s=>`00:${String(s).padStart(2,'0')}.000`;fs.writeFileSync(path.join(out,'v3-walkthrough.vtt'),'WEBVTT\n\n'+beats.map(b=>`${time(b.start)} --> ${time(b.end)}\n${b.voice}`).join('\n\n')+'\n');
 const files=['v3-decision.png','v3-video-poster.png','social-preview-v3.png','v3-tour.gif','v3-walkthrough.mp4','v3-walkthrough-music-only.mp4','v3-walkthrough.vtt'];fs.writeFileSync(path.join(out,'v3-manifest.json'),JSON.stringify({description:'36-second narrated tour, original upbeat music, 15-second GIF. Stock Kokoro am_michael. Benchmark and next-turn results from public research files.',frames_directory_for_local_qa:undefined,files:Object.fromEntries(files.map(f=>[f,{bytes:fs.statSync(path.join(out,f)).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(out,f))).digest('hex')}]))},null,2)+'\n');console.log('Media complete. QA frames:',temp);
})().catch(e=>{console.error(e);process.exitCode=1});
